const routes = {
  root: () => "/",
  login: () => "/login",
  register: () => "register",
  passwordReset: () => "password-reset",
  dashboard: () => "/dashboard",
  attendance: () => "/attendance",
  employee: () => "/employee",
  employeeView: () => "/employee/:id",
  employeeEdit: () => "/employee/:id/edit",
  leave: () => "/leave",
  manageLeave: () => "/leave/manage",
  requestLeave: () => "/leave/request",
  applyLeave: () => "/leave/apply",
  employeeDesignations: () => "/employee/designation",
  employeeDepartment: () => "/employee/department",
  profileSettings: () => "/profile-settings",
  notifications: () => "/notifications",
  helpSupport: () => "/help-support",
  manage: () => "/manage",
  manageUsers: () => "/manage/users",
  createUser: () => "/manage/users/add",
  editUser: () => "/manage/users/:id/edit",
  viewUser: () => "/manage/users/:id",
  manageRoles: () => "/manage/roles",
  manageRolesEdit: () => "/manage/roles/:id/edit",
  manageRolesView: () => "/manage/roles/:id",
  manageRolesAdd: () => "/manage/roles/add",
};

export default routes;
